In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
df = pd.read_csv("datasets/updated_crestwood.csv", index_col=0)

In [3]:
df.head()

Date_Sold   Price  Beds  Baths  Square_Feet
0  2022-02-03  569900     5    4.0         3557
1  2022-02-02  242500     2    1.0         1200
2  2022-01-28  565000     3    2.0         2118
3  2022-01-28  569900     4    4.0         3364
4  2022-01-28  415000     4    4.0         3185

In [4]:
df.dtypes

Date_Sold       object
Price            int64
Beds             int64
Baths          float64
Square_Feet      int64
dtype: object

In [5]:
df = df.astype({'Date_Sold': 'datetime64[ns]'})

In [6]:
df.dtypes

Date_Sold      datetime64[ns]
Price                   int64
Beds                    int64
Baths                 float64
Square_Feet             int64
dtype: object

In [7]:
reg = linear_model.LinearRegression()

In [8]:
reg.fit(df[['Square_Feet', 'Beds', 'Baths']], df['Price'])

LinearRegression()

In [9]:
reg.coef_

array([   72.11544819,  3220.78732651, 59937.95913413])

In [10]:
reg.intercept_

29550.134309156274

In [11]:
# Predict price of homes

# Test 1: 2000 sqft, 3 bed, 2 bath
reg.predict([[2000, 3, 2]])

array([303319.31094118])

In [12]:
# Test 2: 1500 sqft, 2 bed, 2 bath
reg.predict([[1500, 2, 2]])

array([264040.79951861])

In [13]:
# Test 3: 3300 sqft, 4 bed, 2 bath
reg.predict([[3300, 4, 2]])

array([400290.18091743])

In [14]:
df2 = pd.read_csv("datasets/test_housing.csv")

prices = reg.predict(np.array(df2))

In [15]:
df2['Price_Estimate'] = prices
df2

Square_Feet  Beds  Baths  Price_Estimate
0          1000     2    1.0   168045.116288
1          3400     3    3.0   464218.897544
2          2560     3    2.0   343703.961929
3          5200     5    5.5   750313.176778
4          3350     3    3.5   490582.104702
5          3000     3    2.5   405403.738700
6          2750     3    2.0   357405.897085
7          2460     2    2.0   333271.629783
8          6200     6    6.0   855618.391864
9          1500     2    2.0   264040.799519
10         1970     2    2.5   327904.039736
11         4000     4    4.0   570646.912920
12         4600     4    4.5   643885.161403
13         5420     5    4.0   676271.636679
14         1690     2    2.0   277742.734675
15         2275     3    2.0   323151.059194
16         2600     3    2.5   376557.559424
17         3920     4    2.0   445001.758797
18         4530     4    4.0   608868.100462
19         4430     4    3.5   571687.576076
20         6040     5    5.0   780921.173693
21         2580     3    3.0   405084.230027
22         3670     4    3.0   486910.855883
23         3400     4    3.0   467439.684871
24         1840     2    1.5   258591.072337
25         2175     3    2.0   315939.514375
26         4820     5    3.0   573064.408630
27         4490     4    3.0   546045.523400
28         2000     3    2.0   303319.310941
29         1200     2    1.0   182468.205927

In [16]:
df2.to_csv('datasets/estimated.csv')